version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./app:/projects/t-account-picker
    command: npm run watch
    ports:
      - "28900:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true
    tty: true

